#!/usr/bin/env node
// Care Compass plan status — aggregates feature PROGRESS.md files so the shared plan never needs hand-edited status tables.
// Usage:
//   node scripts/plan-status.mjs                 print summary, ready-to-start list, in-progress, blocked
//   node scripts/plan-status.mjs --lane F        filter by lane (S, B, F, C, A, I)
//   node scripts/plan-status.mjs --write         also rewrite the generated section of PROGRESS.md
//   node scripts/plan-status.mjs --json          machine-readable output
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const DEV = path.join(ROOT, "docs", "development");
const args = process.argv.slice(2);
const laneFilter = args.includes("--lane") ? args[args.indexOf("--lane") + 1] : null;
const DONE = new Set(["MERGED TO DEV", "IN DEVELOPMENT TESTING", "READY FOR PRODUCTION", "COMPLETE"]);
const ID_RE = /\b(?:FAM-UI|CAR-UI|ADM-UI|FAM|CAR|ADM|INT|F0|UI)-\d{2}\b/g;

const read = (p) => (fs.existsSync(p) ? fs.readFileSync(p, "utf8") : "");
const cell = (md, label) => {
  const m = md.match(new RegExp(`^\\| ${label} \\| (.+?) \\|\\s*$`, "m"));
  return m ? m[1].trim() : "";
};
const line = (md, prefix) => {
  const m = md.match(new RegExp(`^${prefix}\\s*(.+)$`, "m"));
  return m ? m[1].trim() : "";
};

// Open decisions: OPEN unless the table status says otherwise or an "### OQ-xx — ANSWERED" heading exists.
const decisions = read(path.join(ROOT, "DECISIONS.md"));
const oqStatus = {};
for (const row of decisions.matchAll(/^\| (OQ-\d{2}) \|.*\| ([A-Z ]+) \|\s*$/gm)) oqStatus[row[1]] = row[2].trim();
for (const h of decisions.matchAll(/^### (OQ-\d{2}) — ANSWERED/gm)) oqStatus[h[1]] = "ANSWERED";
const oqOpen = (id) => (oqStatus[id] ?? "OPEN") !== "ANSWERED";

const features = [];
for (const stream of fs.existsSync(DEV) ? fs.readdirSync(DEV) : []) {
  const sdir = path.join(DEV, stream);
  if (!fs.statSync(sdir).isDirectory()) continue;
  for (const slug of fs.readdirSync(sdir)) {
    const prd = read(path.join(sdir, slug, "PRD.md"));
    const prog = read(path.join(sdir, slug, "PROGRESS.md"));
    if (!prd) continue;
    const id = cell(prd, "Feature ID");
    const depsLine = line(prd, "- Features:");
    const blockLine = line(prd, "- Blocking open decisions \\(must be answered before START FEATURE\\):");
    const sprintCell = cell(prd, "Sprint");
    features.push({
      id, slug, stream,
      name: (prd.match(/^# \S+ — (.+)$/m) || [])[1] || slug,
      phase: cell(prd, "Phase"),
      lane: (cell(prd, "Lane").match(/^([A-Z])/) || [])[1] || "?",
      sprint: sprintCell.split(" · ")[0] || "",
      days: (sprintCell.match(/planned (.+)$/) || [])[1] || "",
      branch: cell(prd, "Feature branch").replace(/`/g, ""),
      deps: depsLine === "None" ? [] : [...new Set(depsLine.match(ID_RE) || [])],
      blockers: blockLine === "None" ? [] : [...new Set(blockLine.match(/OQ-\d{2}/g) || [])],
      status: line(prog, "Status:") || "NOT STARTED",
      owner: line(prog, "Owner:") || "unclaimed",
    });
  }
}
const byId = Object.fromEntries(features.map((f) => [f.id, f]));
const dayStart = (d) => Number((d.match(/\d+/) || [99])[0]);
features.sort((a, b) => dayStart(a.days) - dayStart(b.days) || a.id.localeCompare(b.id));

for (const f of features) {
  f.unmetDeps = f.deps.filter((d) => !DONE.has(byId[d]?.status));
  f.openBlockers = f.blockers.filter(oqOpen);
  f.ready = ["NOT STARTED", "PLANNED"].includes(f.status) && f.owner === "unclaimed" &&
    f.sprint !== "POST-SPRINT" && f.unmetDeps.length === 0 && f.openBlockers.length === 0;
}
const shown = laneFilter ? features.filter((f) => f.lane === laneFilter) : features;

if (args.includes("--json")) { console.log(JSON.stringify(shown, null, 2)); process.exit(0); }

const lanes = [...new Set(features.map((f) => f.lane))];
const statusOrder = ["NOT STARTED", "PLANNED", "IN PROGRESS", "BLOCKED", "IMPLEMENTED", "READY FOR PR", "PR OPEN", ...DONE];
let out = `Generated by \`node scripts/plan-status.mjs\` on ${new Date().toISOString().slice(0, 10)} — do not edit by hand.\n\n`;
out += "### Lane summary\n\n| Lane | Features | Done (merged+) | In progress / review | Ready to start | Waiting on dependencies | Waiting on decisions |\n|---|---|---|---|---|---|---|\n";
for (const l of lanes) {
  const fs_ = features.filter((f) => f.lane === l && f.sprint !== "POST-SPRINT");
  out += `| ${l} | ${fs_.length} | ${fs_.filter((f) => DONE.has(f.status)).length} | ${fs_.filter((f) => ["IN PROGRESS", "IMPLEMENTED", "READY FOR PR", "PR OPEN"].includes(f.status)).length} | ${fs_.filter((f) => f.ready).length} | ${fs_.filter((f) => !DONE.has(f.status) && f.unmetDeps.length).length} | ${fs_.filter((f) => !DONE.has(f.status) && f.openBlockers.length).length} |\n`;
}
out += "\n(Post-sprint features excluded from the summary.)\n\n### Ready to start (unclaimed, dependencies merged, no open blocking decision)\n\n";
const ready = shown.filter((f) => f.ready);
out += ready.length ? ready.map((f) => `- **${f.id}** ${f.name} — lane ${f.lane}, planned ${f.days}, branch \`${f.branch}\``).join("\n") : "- None";
out += "\n\n### Claimed / in flight\n\n";
const flight = shown.filter((f) => f.owner !== "unclaimed" && !DONE.has(f.status));
out += flight.length ? flight.map((f) => `- **${f.id}** ${f.name} — ${f.status} — ${f.owner}`).join("\n") : "- None";
out += "\n\n### Not startable yet\n\n| ID | Lane | Planned | Status | Waiting on features | Waiting on decisions |\n|---|---|---|---|---|---|\n";
for (const f of shown.filter((x) => !x.ready && !DONE.has(x.status) && x.owner === "unclaimed" && x.sprint !== "POST-SPRINT"))
  out += `| ${f.id} | ${f.lane} | ${f.days} | ${f.status} | ${f.unmetDeps.join(", ") || "—"} | ${f.openBlockers.join(", ") || "—"} |\n`;
out += "\n### All features\n\n| ID | Feature | Lane | Sprint | Planned | Status | Owner |\n|---|---|---|---|---|---|---|\n";
for (const f of shown) out += `| ${f.id} | ${f.name} | ${f.lane} | ${f.sprint} | ${f.days} | ${f.status} | ${f.owner} |\n`;

console.log(out);
if (args.includes("--write")) {
  const p = path.join(ROOT, "PROGRESS.md");
  const md = read(p);
  const start = "<!-- STATUS:START -->", end = "<!-- STATUS:END -->";
  if (!md.includes(start)) { console.error("PROGRESS.md has no STATUS markers"); process.exit(1); }
  fs.writeFileSync(p, md.slice(0, md.indexOf(start) + start.length) + "\n" + out + "\n" + md.slice(md.indexOf(end)));
  console.error("PROGRESS.md updated");
}
